"""
Pydantic models for nudge-related schemas.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class Diagnosis(BaseModel):
    """Structured diagnosis from the Diagnosis Agent."""
    stuck_point: str = Field(..., description="Where the user is stuck")
    inferred_reason: str = Field(..., description="Why the user appears to be stuck")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence in the diagnosis")


class NudgePayload(BaseModel):
    """Nudge generated by the Coach Agent."""
    nudge_type: str = Field(..., description="tooltip, in_app_chat, or email_draft")
    content: str = Field(..., description="The nudge message content")
    stuck_point: str = Field(..., description="The stuck point this addresses")
    target_element_id: Optional[str] = Field(None, description="Element to attach tooltip to")


class NudgeRecord(BaseModel):
    """Full nudge record for database storage."""
    nudge_id: Optional[str] = None
    user_id: str
    company_id: str
    session_id: Optional[str] = None
    stuck_point: str
    nudge_type: str
    content: str
    diagnosis: Optional[dict] = None
    sent_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = "sent"


class EscalationPayload(BaseModel):
    """Escalation alert for CSMs."""
    user_id: str
    stuck_point: str
    inferred_reason: str
    nudge_log: list[dict] = []
    deep_link: Optional[str] = None
